services:
  app:
    image: nginx:alpine
    container_name: app
    restart: unless-stopped
    volumes:
      - ./app/index.html:/usr/share/nginx/html/index.html:ro
      - ./app/conf/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      app_net:
        ipv4_address: 172.25.0.10

  whoami:
    image: containous/whoami
    container_name: whoami
    restart: unless-stopped
    networks:
      app_net:
        ipv4_address: 172.25.0.20

  reverse-proxy:
    image: nginx:alpine
    container_name: reverse-proxy
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
      - whoami
    networks:
      app_net:
        ipv4_address: 172.25.0.11

networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: "172.25.0.0/24"
